### ISSUE TITLE
Some color changes

### ISSUE THREAD

**Issue by jonkri** [igolskyi/vscode-zenburn-plus-theme#3]
Hi, again!

What do you think of these color changes:

```
  "workbench.colorCustomizations": {
    "editor.findMatchBackground": "#2b2b2b",
    "editor.lineHighlightBackground": "#383838",
    "editor.selectionBackground": "#2b2b2b",
    "editor.selectionHighlightBackground": "#2b2b2b",
    "editorCursor.foreground": "#ffffef"
  },
```

I think they match the colors in the Emacs theme a bit better.

And for me personally, I also think that the change makes text a bit easier to read.

Have a great week! :slightly_smiling_face:

**Comment by igolskyi** [comment]
Hi. Yes, of course, but for now we will apply all the upgrade suggestions only to the "No Bold" version. I think if we get more feedback over time, we will make it (No Bold) the main one.

```
"editorCursor.foreground": "#ffffef"
```
P.S. This color already has the same meaning in the theme.
P.P.S. Also if you liked this theme, you can starred this repo and theme in Marketplace ;)

**Comment by igolskyi** [comment]
@jonkri  you can try the update in v.0.3.4.

**Comment by jonkri** [comment]
Seems to work like a charm, thank you! :slightly_smiling_face:
